//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reuse_Code
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ResponsivewebEntities : DbContext
    {
        public ResponsivewebEntities()
            : base("name=ResponsivewebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_CoustomerDetails> tbl_CoustomerDetails { get; set; }
        public virtual DbSet<tbl_ReuseData> tbl_ReuseData { get; set; }
        public virtual DbSet<tbl_ReuseNameInfo> tbl_ReuseNameInfo { get; set; }
    }
}
