//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reuse_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ReuseData
    {
        public int S_no { get; set; }
        public int ReuseId { get; set; }
        public string FileName { get; set; }
        public string FileData { get; set; }
    
        public virtual tbl_ReuseNameInfo tbl_ReuseNameInfo { get; set; }
    }
}
