//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reuse_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ReuseNameInfo
    {
        public tbl_ReuseNameInfo()
        {
            this.tbl_ReuseData = new HashSet<tbl_ReuseData>();
        }
    
        public int S_no { get; set; }
        public string ReuseType { get; set; }
        public string SubType { get; set; }
    
        public virtual ICollection<tbl_ReuseData> tbl_ReuseData { get; set; }
    }
}
